export enum Labels {
  FEATURED_HEADER = 'Navigating the digital landscape for success',
  FEATURED_BODY = 'Our digital marketing agency helps businesses grow and succeed online through a range of services including SEO, PPC, social media marketing, and content creation.',
  SERVICES_TITLE = 'Services',
  SERVICES_SUBTITLE = 'At our digital marketing agency, we offer a range of services to help businesses grow and succeed online. These services include:',
  SERVICES_FIRST_TITLE = 'Search Engine Optimization',
  SERVICES_SECOND_TITLE = 'Pay-per-click Advertising',
  SERVICES_THIRD_TITLE = 'Social Media Marketing',
  SERVICES_FOURTH_TITLE = 'Email Marketing',
  SERVICES_FIFTH_TITLE = 'Content Creator',
  SERVICES_SIXTH_TITLE = 'Analytics and Tracking',
  MAKE_HAPPEN_TITLE = 'Let’s make things happen',
  MAKE_HAPPEN_SUBTITLE = 'Contact us today to learn more about how our digital marketing services can help your business grow and succeed online.',
  WORKING_PROGRESS_TITLE = 'Our Working Process',
  WORKING_PROGRESS_SUBTITLE = 'Step-by-Step Guide to Achieving Your Business Goals',
  TEAM_TITLE = 'Team',
  TEAM_SUBTITLE = 'Meet the skilled and experienced team behind our successful digital marketing strategies',
  CONTACT_US_TITLE = 'Contact Us',
  CONTACT_US_SUBTITLE = `Connect with Us: Let's Discuss Your Digital Marketing Needs`,
  NAME = 'Name',
  EMAIL = 'Email',
  MESSAGE = 'Message',
  CONTACT_US_BODY = 'Contact us',
  RIGHTS = '© 2023 Positivus. All Rights Reserved.',
}